### ISSUE TITLE
Create Cluster workflow for Azure

### ISSUE THREAD

**Issue by tarokkk** [banzaicloud/pipeline#1969]
This is an epic issue for the different Azure activites

Required issues:
- [x] #1970 Create Azure NSG activity
- [x] #1971 Create Azure VNET activity
- [x] #1972 Create Azure VMSS activity
- [x] #1973 Create Azure Bootstrap command
- [x] #1974 Create Azure LoadBalancer activity
