### ISSUE TITLE
Managed DNS config

### ISSUE THREAD

**Issue by siliconbrain** [banzaicloud/pipeline#2070]
*Managed DNS configurations* can be used to store predefined values for the managed DNS feature. These configs are stored per organization and contain the following:
* a provider,
* a credential for accessing the provider,
* a DNS zone.

The provider should be one supported by the managed DNS feature (possibly all providers supported by [ExternalDNS](https://github.com/kubernetes-incubator/external-dns)).
The credential is a reference to a secret and should be validated against the provider if possible.
The DNS zone will be passed to the managed DNS feature configuration as the DNS filter.

The managed DNS configs should be listable with their details, e.g. by the web UI to
present the user with a list for selecting a config, or the CLI to create a questionare similar in function to the list on the web UI.

When there are multiple configurations available for an organization, a default config can be selected by the user. When there is exactly one config available it is selected as default automatically. When the currently default config is deleted one of the remaining configs—consistently, not at random—is selected as default.

Apart from members of an organization being able to add, modify, and remove configs, we propose the following optionally enabled template generators that can extend an organization's config set when invoked:
* global (i.e. control plane wide) managed DNS config template
* AutoDNS

## Global managed DNS config template
The *global managed DNS config template* can be set up by the control plane administrator when the control plane is created—or later, by accessing the control plane configuration directly. This template specifies
* ***a provider***,
* a means to access ***a credential*** (initially a path to a file containing the credential), and
* ***a DNS zone*** that will be used as a base for generating a unique subdomain for an organization.

The referenced credential will be added to the organization's secrets—if necessary—when generating the config.

## AutoDNS
*AutoDNS* can be used to generate the values for creating a managed DNS config. When invoked, AutoDNS returns
* ***a DNS zone*** unique to the requesting organization,
* ***a provider***, and
* ***a credential*** for managing the DNS zone at the provider.

The credential is added to the organization's secrets.

# Tasks
* [ ] storage of org-level configs sets
* [ ] internal API for listing, adding, modifying and deleting org-level configs
* [ ] REST API for listing, adding, modifying, and removing org-level configs
* [ ] web UI for viewing, adding, modifying, and removing org-level configs
* [ ] CLI commands for listing, adding, modifying, and removing org-level configs
* [ ] config section for setting global managed DNS config template details
* [ ] config section for setting AutoDNS details
* [ ] internal API for listing and invoking any enabled config generators
* [ ] REST API for listing and invoking any enabled config generators
* [ ] web UI for listing and invoking any enabled config generators
* [ ] CLI command(s) for listing and invoking any enabled config generators

**Comment by sagikazarmark** [comment]
DNS integrated service is already implemented. AutoDNS will be implemented later.
